# Generated by Django 4.1.7 on 2023-04-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('url', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, max_length=50, verbose_name='Название проблемы')),
                ('content', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('img_before', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото до')),
                ('img_after', models.ImageField(default=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото до'), upload_to='photos/%Y/%m/%d/', verbose_name='Фото после')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.CharField(default='Новая', max_length=20, verbose_name='Статус заявки')),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категории')),
            ],
        ),
    ]
