# Generated by Django 4.1.7 on 2023-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='img_after',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото после'),
        ),
    ]
