# Generated by Django 4.1.7 on 2023-04-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy_policy',
            field=models.BooleanField(default=False, verbose_name='Обработка персональных данных'),
        ),
    ]
