# Generated by Django 4.1.7 on 2023-04-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_burger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burger',
        ),
    ]
