# Generated by Django 4.1.7 on 2023-04-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_privacy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='privacy_policy',
        ),
    ]
