# Generated by Django 4.1.7 on 2023-04-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_api_cat_alter_api_photo_alter_api_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='description',
        ),
        migrations.AlterField(
            model_name='api',
            name='problem',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название проблемы'),
        ),
    ]
