# Generated by Django 4.1.7 on 2023-04-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_api_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Post',
        ),
    ]
